import Link from "next/link";
import Logo from "./components/Logo";
import Navigation from "./components/Navigation";

export const metadata = {
  title: "The Wild Oasis",
  // description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Logo />
          <Link href='/'>The Wild Oasis</Link>
          <Navigation />
        </header>
        <main>{children}</main>
        <footer>
          Copyright &copy; 2023 The Wild Oasis. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
